title: Friday Night Funkin Mods
description: Click On these links for FNF mods and the real game
template:
  repo: friday-night-funkin-mods-template
  name: friday-night-funkin-mods
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
